### ISSUE TITLE
The code disables ssh on port 22 by default

### ISSUE THREAD

**Issue by mbruzek** [mbruzek/layer-ssh-server#1]
The current code makes sshd listen only on one port, but it can listen on many ports. Since the default is not 22 that breaks the ability to `juju ssh ssh-server/0` to the server. I need some more advanced bash (or change the code to python) to leave "Port 22" in the config file and only add a new Port definition in the new case, replace the added Port definition in a config-changed case.

**Comment by kwmonroe** [comment]
For simplicity, I think you should remove all `Port` references all the time, and add back the configured value(s).  So in your config handler, something like:

```
# remove all references to Port, since we're going to add them based on our config
sed -i -e '/Port/d' /etc/ssh/sshd_config

# add our Ports back (assuming the config value takes a space separated list)
for port in `config-get port`; do
  echo "Port $port" >> /etc/ssh/sshd_config
done
```
